package no.nav.tsm.diagnoser.codes

import no.nav.tsm.diagnoser.Diagnose
import no.nav.tsm.diagnoser.DiagnoseType

private val ICPC2_CODES = listOf(
  /** CODEGEN START **/
  Diagnose(system = DiagnoseType.ICPC2, code = "A01", text = "Smerte generell/flere steder"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A02", text = "Frysninger"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A03", text = "Feber"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A04", text = "Slapphet/tretthet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A05", text = "Sykdomsfølelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A06", text = "Besvimelse/synkope"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A07", text = "Bevisstløshet/koma"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A08", text = "Hevelse/oppfylning IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A09", text = "Svetteproblemer"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A10", text = "Blødning IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A11", text = "Brystsmerte IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A13", text = "Engstelig for behandling"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A16", text = "Irritabelt/urolig spedbarn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A18", text = "Bekymret/opptatt av utseende IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A191", text = "Kjønnsinkongruens"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A20", text = "Dødshjelp diskusjon/spørsmål om"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A21", text = "Økt risiko for ondartet svulst"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A23", text = "Risiko for sykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A25", text = "Engstelig for døden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A26", text = "Engstelig for kreft IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A27", text = "Engstelig for sykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A28", text = "Redusert funksjonsevne IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A29", text = "Generelle symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A70", text = "Tuberkulose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A71", text = "Meslinger"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A72", text = "Vannkopper"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A73", text = "Malaria"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A74", text = "Røde hunder"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A75", text = "Mononukleose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A76", text = "Virussykdom med utslett IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A77", text = "Virussykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A78", text = "Infeksjonssykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A79", text = "Ondartet svulst IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A80", text = "Skade/traume IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A81", text = "Multiple skader/traumer"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A82", text = "Følgetilstand etter skade/traume"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A84", text = "Legemiddelforgiftning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A85", text = "Bivirkning av legemiddel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A86", text = "Toksisk virkning av ikke-medisinsk stoff"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A87", text = "Komplikasjon etter medisinsk behandling"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A88", text = "Skadevirkning av fysisk faktor"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A89", text = "Komplikasjoner/problemer med protese"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A90", text = "Medfødt feil IKA/multiple medfødte feil"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A91", text = "Unormalt resultat ved undersøkelse IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A92", text = "Allergi/allergisk reaksjon IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A93", text = "Prematurt/immaturt født barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A94", text = "Perinatal sykelighet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A95", text = "Perinatal død"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A96", text = "Død/dødsfall IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A97", text = "Kontakt/undersøkelse for administrativt formål"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A98", text = "Individforebyggende tiltak"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A981", text = "Livmorhalsprøve"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A981", text = "Livmorhalsprøve"),
  Diagnose(system = DiagnoseType.ICPC2, code = "A99", text = "Helseproblem/sykdom ikke spesifisert/lokalisert"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B02", text = "Lymfeknuter forstørrede/smertefulle"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B04", text = "Blod/blodsystemet symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B25", text = "Engstelig for hiv/aids"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B26", text = "Engstelig for kreft i blod- og lymfesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B27", text = "Engstelig for sykdom i blod- og lymfesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B28", text = "Redusert funksjonsevne pga blod/lymfe-problem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B29", text = "Blod/lymfesystem symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B70", text = "Lymfadenitt akutt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B71", text = "Lymfadenitt kronisk/uspesifikk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B72", text = "Hodgkins sykdom/lymfom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B73", text = "Leukemi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B74", text = "Ondartet svulst i blod/lymfesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B75", text = "Godartet/uspesifisert svulst i blod/lymfesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B76", text = "Miltruptur traumatisk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B77", text = "Skade i blod/lymfesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B78", text = "Arvelig hemolytisk anemi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B79", text = "Medfødt feil i blod/lymfesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B80", text = "Jernmangelanemi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B81", text = "Anemi ved vitamin B12-/folsyremangel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B82", text = "Anemi IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B83", text = "Purpura/koagulasjonsdefekt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B84", text = "Unormale hvite blodceller"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B87", text = "Forstørret milt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B90", text = "Hiv-sykdom/aids"),
  Diagnose(system = DiagnoseType.ICPC2, code = "B99", text = "Blod/lymfe/milt sykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D01", text = "Abdominalsmerte/krampe generell"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D02", text = "Abdominalsmerte epigastriet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D03", text = "Halsbrann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D04", text = "Endetarmssmerte"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D05", text = "Perianal kløe"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D06", text = "Abdominalsmerte lokalisert IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D07", text = "Dyspepsi/fordøyelsesbesvær"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D08", text = "Flatulens/oppblåsthet/raping"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D09", text = "Kvalme"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D10", text = "Oppkast/brekninger"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D11", text = "Diaré"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D12", text = "Forstoppelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D13", text = "Gulsott"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D14", text = "Oppkast med blod/hematemese"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D15", text = "Melena"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D16", text = "Rektalblødning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D17", text = "Inkontinens avføring"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D18", text = "Endring i avføring/avføringsvane"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D19", text = "Tenner/tannkjøtt symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D20", text = "Munn/tunge/leppe symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D21", text = "Svelgebesvær"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D23", text = "Forstørret lever"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D24", text = "Abdominal oppfylling/kul IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D25", text = "Utspilt abdomen"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D26", text = "Engstelig for kreft i fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D27", text = "Engstelig for sykdom i fordøyelsessystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D28", text = "Redusert funksjonsevne pga fordøyelsesproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D29", text = "Fordøyelsessystemet symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D70", text = "Tarminfeksjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D71", text = "Kusma"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D72", text = "Virushepatitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D73", text = "Gastroenteritt antatt infeksiøs"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D74", text = "Ondartet svulst i magesekk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D75", text = "Ondartet svulst i tykktarm/endetarm"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D76", text = "Ondartet svulst i bukspyttkjertel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D77", text = "Ondartet svulst i fordøyelsessystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D78", text = "Godartet/uspesifisert svulst i fordøyelsesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D79", text = "Fremmedlegeme i fordøyelsesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D80", text = "Skade i fordøyelsessystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D81", text = "Medfødt feil i fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D82", text = "Tenner/tannkjøtt sykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D83", text = "Munn/tunge/lepper sykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D84", text = "Spiserørssykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D85", text = "Sår i tolvfingertarm"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D86", text = "Magesår IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D87", text = "Funksjonelle plager i magesekk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D88", text = "Appendisitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D89", text = "Lyskebrokk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D90", text = "Mellomgulvsbrokk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D91", text = "Abdominalt brokk IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D92", text = "Divertikkelsykdom i tarm"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D93", text = "Irritabel tarm-syndrom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D94", text = "Kronisk enteritt/ulcerøs kolitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D95", text = "Analfissur/perianal abscess"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D96", text = "Orme-/parasittsykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D97", text = "Leversykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D98", text = "Galleveisbetennelse/gallestein"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D99", text = "Sykdom i fordøyelsessystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D991", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D992", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D993", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D994", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D995", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D996", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D997", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D998", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "D999", text = "Utbruddssykdom definert av FHI, fordøyelsessystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F01", text = "Øyesmerte"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F02", text = "Rødt øye"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F03", text = "Tåreflod/sekresjon øye"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F04", text = "Synlige flekker/tråder i synsfeltet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F05", text = "Synsforstyrrelse IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F13", text = "Øye unormal følelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F14", text = "Øye unormal bevegelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F15", text = "Øye unormalt utseende"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F16", text = "Øyelokk symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F17", text = "Briller symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F18", text = "Kontaktlinser symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F27", text = "Engstelig for øyesykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F28", text = "Redusert funksjonsevne pga øyeproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F29", text = "Øye symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F70", text = "Infeksiøs konjunktivitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F71", text = "Allergisk konjunktivitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F72", text = "Øyelokkbetennelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F73", text = "Øye infeksjon/betennelse IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F74", text = "Svulst i øye/øyehule"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F75", text = "Kontusjon/blødning i øye"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F76", text = "Fremmedlegeme i øye"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F79", text = "Skade i øye IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F80", text = "Tåreveisstenose/atresi hos spedbarn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F81", text = "Medfødt feil i øye IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F82", text = "Netthinneløsning/rift"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F83", text = "Retinopati"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F84", text = "Makuladegenerasjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F85", text = "Hornhinnesår"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F86", text = "Trakom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F91", text = "Brytningsforstyrrelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F92", text = "Grå stær/katarakt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F93", text = "Glaukom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F94", text = "Blindhet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F95", text = "Skjeling/strabisme"),
  Diagnose(system = DiagnoseType.ICPC2, code = "F99", text = "Øyesykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H01", text = "Øresmerte/øreverk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H02", text = "Hørsel symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H03", text = "Øresus"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H04", text = "Øreflod/sekresjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H05", text = "Blødning øre"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H13", text = "Øreplugg/øretetthet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H15", text = "Bekymret/opptatt av ørenes utseende"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H27", text = "Engstelig for hørselsproblemer/øresykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H28", text = "Redusert funksjonsevne pga øreproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H29", text = "Øre symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H70", text = "Ytre øre betennelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H71", text = "Mellomørebetennelse akutt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H72", text = "Mellomørebetennelse serøs"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H73", text = "Tuba auditiva betennelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H74", text = "Mellomørebetennelse kronisk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H75", text = "Svulst i øre"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H76", text = "Fremmedlegeme i øre"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H77", text = "Perforert trommehinne IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H78", text = "Overflateskade på ytre øre"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H79", text = "Skade øre IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H80", text = "Medfødt feil i øre"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H81", text = "Ørevoks"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H82", text = "Svimmelhetssyndrom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H83", text = "Otosklerose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H84", text = "Hørselstap aldersbetinget"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H85", text = "Hørselstap pga støyskade"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H86", text = "Døvhet/hørselstap IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "H99", text = "Øresykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K01", text = "Smerte relatert til hjertet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K02", text = "Trykk/sammensnøring hjertet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K03", text = "Smerte relatert til kretsløpet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K04", text = "Hjertebank"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K05", text = "Uregelmessige hjerteslag IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K06", text = "Utvidede vener"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K07", text = "Hovne ankler/ødem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K22", text = "Økt risiko for hjerte-karsykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K24", text = "Engstelig for hjertesykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K25", text = "Engstelig for høyt blodtrykk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K27", text = "Engstelig for hjerte-karsykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K28", text = "Redusert funksjonsevne pga hjerte-karproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K29", text = "Hjerte-karsystemet symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K70", text = "Infeksjon i hjerte-karsystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K71", text = "Reumatisk feber/hjertesykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K72", text = "Svulst i hjerte"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K73", text = "Medfødt feil i hjerte-karsystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K74", text = "Iskemisk hjertesykdom med angina pectoris"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K75", text = "Akutt hjerteinfarkt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K76", text = "Iskemisk hjertesykdom kronisk IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K77", text = "Hjertesvikt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K78", text = "Atrieflimmer/flutter"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K79", text = "Paroksysmal takykardi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K80", text = "Hjertearytmi IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K81", text = "Bilyd hjerte/arterier IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K82", text = "Pulmonal hjertesykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K83", text = "Hjerteklaffesykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K84", text = "Hjertesykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K85", text = "Forhøyet blodtrykk IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K86", text = "Hypertensjon ukomplisert"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K87", text = "Hypertensjon med organkomplikasjoner"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K88", text = "Postural hypotensjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K89", text = "Anfall med forbigående cerebral iskemi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K90", text = "Hjerneslag"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K91", text = "Cerebrovaskulær sykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K92", text = "Aterosklerose/perifer karsykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K93", text = "Lungeemboli"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K94", text = "Årebetennelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K95", text = "Åreknuter på underekstremitet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K96", text = "Hemoroider"),
  Diagnose(system = DiagnoseType.ICPC2, code = "K99", text = "Hjerte-karsykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L01", text = "Nakke symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L02", text = "Rygg symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L03", text = "Korsrygg symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L04", text = "Brystkasse symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L05", text = "Flanke/armhule symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L07", text = "Kjeve symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L08", text = "Skulder symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L09", text = "Arm symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L10", text = "Albue symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L11", text = "Håndledd symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L12", text = "Hånd/finger symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L13", text = "Hofte symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L14", text = "Legg/lår symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L15", text = "Kne symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L16", text = "Ankel symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L17", text = "Fot/tå symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L18", text = "Utbredte muskelsmerter/fibromyalgi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L19", text = "Muskel symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L20", text = "Ledd symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L26", text = "Engstelig for kreft i muskel- og skjelettsystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L27", text = "Engstelig for sykdom i muskel- og skjelettsystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L28", text = "Redusert funksjonsevne pga muskel-skjelettproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L29", text = "Muskel- og skjelettsystemet symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L70", text = "Infeksjon i muskel- og skjelettsystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L71", text = "Ondartet svulst i muskel- og skjelettsystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L72", text = "Brudd underarm"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L73", text = "Brudd legg/ankel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L74", text = "Brudd hånd/fot"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L75", text = "Brudd lårben/lårhals"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L76", text = "Brudd IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L77", text = "Forstuving/forstrekking ankel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L78", text = "Forstuving/forstrekking kne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L79", text = "Forstuving/forstrekking ledd IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L80", text = "Dislokasjon/subluksasjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L81", text = "Skade i muskel- og skjelettsystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L82", text = "Medfødt feil i muskel- og skjelettsystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L83", text = "Nakkesyndrom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L84", text = "Ryggsyndrom uten smerteutstråling"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L85", text = "Ervervet deformitet av ryggsøylen"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L86", text = "Ryggsyndrom med smerteutstråling"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L87", text = "Bursitt/tendinitt/synovitt IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L88", text = "Reumatoid artritt/reumatisk sykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L89", text = "Hofteleddsartrose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L90", text = "Kneleddsartrose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L91", text = "Artrose IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L92", text = "Skuldersyndrom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L93", text = "Tennisalbue/lateral epikondylitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L94", text = "Osteokondrose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L95", text = "Osteoporose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L96", text = "Akutt indre kneskade"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L97", text = "Godartet/uspesifisert svulst  i muskel- og skjelettsystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L98", text = "Ervervet deformitet av ekstremitet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "L99", text = "Muskel- og skjelettsykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N01", text = "Hodepine"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N03", text = "Ansiktssmerte"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N04", text = "Restless legs"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N05", text = "Prikking/parestesi i hender/føtter"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N06", text = "Forstyrrelser i hudens følsomhet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N07", text = "Krampeanfall/kramper"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N08", text = "Unormale/ufrivillige bevegelser"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N16", text = "Forstyrrelse i lukt/smak"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N17", text = "Svimmelhet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N18", text = "Lammelse/svakhet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N19", text = "Talevansker"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N26", text = "Engstelig for kreft i nervesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N27", text = "Engstelig for sykdom i nervesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N28", text = "Redusert funksjonsevne pga problem i nervesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N29", text = "Nervesystemet symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N70", text = "Poliomyelitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N71", text = "Meningitt/encefalitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N72", text = "Stivkrampe"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N73", text = "Infeksjon i sentralnervesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N74", text = "Ondartet svulst i nervesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N75", text = "Godartet svulst i nervesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N76", text = "Uspesifisert svulst i nervesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N79", text = "Hjernerystelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N80", text = "Hodeskade IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N81", text = "Skade i nervesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N85", text = "Medfødt feil i nervesystemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N86", text = "Multippel sklerose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N87", text = "Parkinsonisme"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N88", text = "Epilepsi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N89", text = "Migrene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N90", text = "Cluster-hodepine"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N91", text = "Facialisparese"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N92", text = "Trigeminusnevralgi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N93", text = "Carpal tunnel syndrom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N94", text = "Perifer nevropati"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N95", text = "Tensjonshodepine"),
  Diagnose(system = DiagnoseType.ICPC2, code = "N99", text = "Sykdom i nervesystemet IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P01", text = "Følelse av angst/nervøsitet/anspenthet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P02", text = "Psykisk ubalanse situasjonsbetinget"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P03", text = "Depresjonsfølelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P04", text = "Irritabel atferd/følelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P05", text = "Senilitet, atferd/følelse gammel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P06", text = "Søvnforstyrrelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P07", text = "Seksuell drift/lyst hemmet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P08", text = "Seksuell tilfredsstillelse hemmet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P09", text = "Seksuell legning bekymring for"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P10", text = "Stamming/tics"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P11", text = "Spiseforstyrrelse hos barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P12", text = "Sengevæting/enuresis IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P13", text = "Enkoprese"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P15", text = "Kronisk alkoholmisbruk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P16", text = "Akutt alkoholmisbruk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P17", text = "Tobakkmisbruk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P18", text = "Legemiddelmisbruk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P19", text = "Stoffmisbruk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P20", text = "Hukommelsesforstyrrelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P22", text = "Atferdsforstyrrelse hos barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P23", text = "Atferdsforstyrrelse hos ungdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P24", text = "Spesifikke utviklingsforstyrrelser"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P25", text = "Livsfaseproblem hos voksen"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P27", text = "Engstelig for psykisk sykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P28", text = "Redusert funksjonsevne pga psykisk problem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P29", text = "Psykiske symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P70", text = "Demens"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P71", text = "Organisk psykisk lidelse IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P72", text = "Schizofreni"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P73", text = "Bipolar lidelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P74", text = "Angstlidelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P75", text = "Dissosiativ/somatoform lidelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P76", text = "Depressiv lidelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P77", text = "Selvmord/selvmordsforsøk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P78", text = "Nevrasteni"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P79", text = "Fobi/obsessiv-kompulsiv lidelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P80", text = "Personlighetsforstyrrelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P81", text = "Hyperkinetisk forstyrrelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P82", text = "Posttraumatisk stresslidelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P85", text = "Psykisk utviklingshemning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P86", text = "Anorexia nervosa/bulimi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P98", text = "Psykose IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "P99", text = "Psykisk lidelse IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R01", text = "Smerte i luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R02", text = "Kortpustethet/dyspné"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R03", text = "Piping i brystet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R04", text = "Pusteproblem IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R05", text = "Hoste"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R06", text = "Neseblødning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R07", text = "Nysing/tetthet i nese"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R08", text = "Nese symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R09", text = "Bihule symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R21", text = "Hals symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R23", text = "Stemme symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R24", text = "Blodig oppspytt/hemoptyse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R25", text = "Unormalt oppspytt/ekspektorat"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R26", text = "Engstelig for kreft i luftveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R27", text = "Engstelig for sykdom i luftveiene IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R28", text = "Redusert funksjonsevne pga luftveisproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R29", text = "Luftveiene symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R33", text = "Mikrobiologisk/immunologisk prøve"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R71", text = "Kikhoste"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R72", text = "Streptokokkhals"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R73", text = "Nesebyll"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R74", text = "Akutt øvre luftveisinfeksjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R75", text = "Bihulebetennelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R76", text = "Akutt tonsillitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R77", text = "Akutt laryngitt/trakeitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R78", text = "Akutt bronkitt/bronkiolitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R79", text = "Kronisk bronkitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R80", text = "Influensa"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R81", text = "Lungebetennelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R82", text = "Pleuritt IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R83", text = "Luftveisinfeksjon IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R84", text = "Ondartet svulst i bronkie/lunge"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R85", text = "Ondartet svulst i luftveiene IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R86", text = "Godartet svulst i luftveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R87", text = "Fremmedlegeme i nese/larynks/bronkie"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R88", text = "Skade i luftveiene IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R89", text = "Medfødt feil i luftveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R90", text = "Hypertrofi av tonsiller/adenoid vev"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R92", text = "Uspesifisert svulst i luftveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R95", text = "Kronisk obstruktiv lungesykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R96", text = "Astma"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R97", text = "Allergisk rhinitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R98", text = "Hyperventileringssyndrom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R99", text = "Luftveissykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R991", text = "Covid-19 (mistenkt/sannsynlig)"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R992", text = "Covid-19 (bekreftet)"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R993", text = "Utbruddssykdom definert av FHI, luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R994", text = "Utbruddssykdom definert av FHI, luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R995", text = "Utbruddssykdom definert av FHI, luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R996", text = "Utbruddssykdom definert av FHI, luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R997", text = "Utbruddssykdom definert av FHI, luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R998", text = "Utbruddssykdom definert av FHI, luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "R999", text = "Utbruddssykdom definert av FHI, luftveier"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S01", text = "Smerte/ømhet i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S02", text = "Hudkløe"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S03", text = "Vorter"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S04", text = "Lokalisert hevelse/kul i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S05", text = "Utbredte hevelser/kuler i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S06", text = "Lokalisert utslett i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S07", text = "Utbredt utslett i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S08", text = "Forandring av hudfargen IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S09", text = "Infeksjon i finger/tå"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S10", text = "Abscess/furunkel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S11", text = "Hudinfeksjon posttraumatisk"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S12", text = "Insektstikk/bitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S13", text = "Bitt av dyr/menneske"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S14", text = "Forbrenning/skålding"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S15", text = "Fremmedlegeme i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S16", text = "Kontusjon/slag hud"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S17", text = "Skrubbsår/blemmer"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S18", text = "Åpent sår/kutt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S19", text = "Skade i hud/underhud IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S20", text = "Liktorn/fortykket underhud"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S21", text = "Hudstruktur symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S22", text = "Negl symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S23", text = "Håravfall/skallethet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S24", text = "Hår/hodebunn symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S26", text = "Engstelig for kreft i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S27", text = "Engstelig for hudsykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S28", text = "Redusert funksjonsevne pga hudproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S29", text = "Hud symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S70", text = "Herpes zoster"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S71", text = "Herpes simplex IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S72", text = "Infestasjon av midd"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S73", text = "Infestasjon av parasitt IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S74", text = "Ringorm/hudsopp IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S75", text = "Candidainfeksjon i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S76", text = "Hudinfeksjon IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S77", text = "Ondartet svulst i huden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S78", text = "Lipom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S79", text = "Godartet/uspesifisert svulst i huden IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S80", text = "Solutløst keratose/solforbrenning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S81", text = "Hemangiom/lymfangiom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S82", text = "Pigmentnevus"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S83", text = "Medfødt feil i hud/underhud IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S84", text = "Brennkopper"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S85", text = "Pilonidalcyste/-fistel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S86", text = "Seboréisk dermatitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S87", text = "Atopisk dermatitt/eksem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S88", text = "Kontaktdermatitt/allergisk dermatitt IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S89", text = "Bleiedermatitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S90", text = "Pityriasis rosea"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S91", text = "Psoriasis"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S92", text = "Svettekjertelsykdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S93", text = "Talgcyste"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S94", text = "Inngrodd negl"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S95", text = "Molluscum contagiosum"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S96", text = "Akne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S97", text = "Kronisk hudsår"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S98", text = "Urticaria"),
  Diagnose(system = DiagnoseType.ICPC2, code = "S99", text = "Hud/underhud sykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T01", text = "Økt tørste"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T02", text = "Økt matlyst"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T03", text = "Nedsatt matlyst"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T04", text = "Ernæringsproblem hos spedbarn/barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T05", text = "Ernæringsproblem hos voksen"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T07", text = "Vektøkning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T08", text = "Vekttap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T10", text = "Forsinket vekst"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T11", text = "Uttørring"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T26", text = "Engstelig for kreft i det endokrine systemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T27", text = "Engstelig for sykd endokr/metabolske syst/ernæringssykd IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T28", text = "Redusert funksjonsevne pga endokr/metabolsk/ernæringsproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T29", text = "Endokrin/metabolsk/ernæring symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T70", text = "Infeksjon i det endokrine systemet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T71", text = "Ondartet svulst i tyreoidea"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T72", text = "Godartet svulst i tyreoidea"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T73", text = "Svulst i endokrine organ IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T78", text = "Ductus/cystis tyreoglossus"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T80", text = "Medfødt feil i endokrine/metabolske system IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T81", text = "Struma"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T82", text = "Fedme"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T83", text = "Overvekt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T85", text = "Hypertyreose/tyreotoksikose"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T86", text = "Hypotyreose/myksødem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T87", text = "Hypoglykemi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T89", text = "Diabetes type 1"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T90", text = "Diabetes type 2"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T91", text = "Vitaminmangel/ernæringsforstyrrelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T92", text = "Urinsyregikt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T93", text = "Lipidstoffskifte forstyrrelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "T99", text = "Endokrin/metabolsk/ernæringssykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U01", text = "Smerte ved vannlating"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U02", text = "Hyppig vannlating"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U04", text = "Urininkontinens"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U05", text = "Vannlatingsproblemer IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U06", text = "Hematuri"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U07", text = "Urin symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U08", text = "Urinretensjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U13", text = "Blære symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U14", text = "Nyre symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U26", text = "Engstelig for kreft i urinveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U27", text = "Engstelig for sykdom i urinveiene IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U28", text = "Redusert funksjonsevne pga urinveisproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U29", text = "Urinveier symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U70", text = "Nyrebekkenbetennelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U71", text = "Cystitt/urinveisinfeksjon IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U72", text = "Uretritt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U75", text = "Ondartet svulst i nyre"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U76", text = "Ondartet svulst i urinblære"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U77", text = "Ondartet svulst i urinveiene IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U78", text = "Godartet svulst i urinveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U79", text = "Uspesifisert svulst i urinveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U80", text = "Skade i urinveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U85", text = "Medfødt feil i urinveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U88", text = "Glomerulonefritt/nefropati"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U90", text = "Ortostatisk proteinuri"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U95", text = "Stein i urinveiene"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U98", text = "Unormal urinprøve IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "U99", text = "Urinveissykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W01", text = "Spørsmål om svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W02", text = "Engstelig for svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W03", text = "Blødning i svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W05", text = "Kvalme/brekninger i svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W10", text = "Prevensjon postkoital antikonsepsjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W11", text = "Prevensjon p-pille"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W12", text = "Prevensjon spiral"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W13", text = "Sterilisering kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W14", text = "Prevensjon IKA kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W15", text = "Infertilitet kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W17", text = "Blødning etter fødsel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W18", text = "Postpartum symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W19", text = "Amming symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W21", text = "Bekymret/opptatt av utseende i svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W27", text = "Engstelig for komplikasjoner ved svangerskap/fødsel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W28", text = "Redusert funksjonsevne pga svangerskapsproblem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W29", text = "Svangerskap/fødsel symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W70", text = "Infeksjon/sepsis i barseltid"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W71", text = "Infeksjon som kompliserer svangerskap IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W72", text = "Ondartet svulst knyttet til svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W73", text = "Godartet/uspesifisert svulst knyttet til svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W75", text = "Skade som kompliserer svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W76", text = "Medfødt feil som kompliserer svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W78", text = "Svangerskap bekreftet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W781", text = "Svangerskapskontroll"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W79", text = "Uønsket svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W80", text = "Ekstrauterint svangerskap"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W81", text = "Svangerskapsforgiftning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W82", text = "Abort spontan"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W83", text = "Abort fremkalt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W84", text = "Svangerskap høyrisiko"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W85", text = "Svangerskapsdiabetes"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W90", text = "Ukomplisert fødsel levendefødt barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W91", text = "Ukomplisert fødsel dødfødt barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W92", text = "Komplisert fødsel levendefødt barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W93", text = "Komplisert fødsel dødfødt barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W94", text = "Mastitt i barseltid"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W95", text = "Brystsykdom i svangerskap/barseltid IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W96", text = "Komplikasjoner i barseltid IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "W99", text = "Svangerskap/fødsel/barseltid sykdom IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X01", text = "Smerte i  kjønnsorgan kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X02", text = "Menstruasjonssmerter"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X03", text = "Intermenstruelle smerter"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X04", text = "Smerte ved samleie kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X05", text = "Menstruasjon sparsom/sjelden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X06", text = "Menstruasjon kraftig"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X07", text = "Menstruasjon uregelmessig/hyppig"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X08", text = "Intermenstruell blødning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X09", text = "Premenstruelle symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X10", text = "Forskyvning av menstruasjon"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X11", text = "Klimakterium symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X12", text = "Postmenopausal blødning"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X13", text = "Blødning etter samleie"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X14", text = "Utflod fra skjeden"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X15", text = "Skjede symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X16", text = "Vulva symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X17", text = "Underliv symptomer/plager kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X18", text = "Smerte i bryst kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X19", text = "Kul i bryst IKA kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X20", text = "Brystvorte symptomer/plager kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X21", text = "Bryst symptomer/plager IKA kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X22", text = "Bekymret/opptatt av brystenes utseende kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X23", text = "Engstelig for kjønnssykdom kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X24", text = "Engstelig for seksuell dysfunksjon kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X25", text = "Engstelig for kreft i kjønnsorgan kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X26", text = "Engstelig for brystkreft kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X27", text = "Engstelig for sykdom i kjønnsorgan/bryst IKA kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X28", text = "Redusert funksjonsevne pga problem i kjønnsorgan kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X29", text = "Kjønnsorgan symptomer/plager IKA kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X70", text = "Syfilis kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X71", text = "Gonokokkinfeksjon kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X72", text = "Candidainfeksjon urogenitalt kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X73", text = "Trikomonasinfeksjon urogenitalt kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X74", text = "Underlivsinfeksjon IKA kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X75", text = "Ondartet svulst i livmorhals"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X76", text = "Ondartet svulst i bryst kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X77", text = "Ondartet svulst i kvinnelige kjønnsorgan  IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X78", text = "Godartet svulst i livmor"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X79", text = "Godartet svulst i bryst kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X80", text = "Godartet svulst i kvinnelige kjønnsorgan IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X81", text = "Uspesifisert svulst i kvinnelige kjønnsorgan IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X82", text = "Skade i kvinnelige kjønnsorgan"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X83", text = "Medfødt feil i kvinnelige kjønnsorgan"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X84", text = "Vaginitt/vulvitt IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X85", text = "Sykdom i livmorhals IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X86", text = "Cytologi livmorhals unormal"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X87", text = "Fremfall av kvinnelige kjønnsorgan"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X88", text = "Godartet mammadysplasi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X89", text = "Premenstruelt tensjonssyndrom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X90", text = "Genital herpesvirusinfeksjon kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X91", text = "Condylomata acuminata kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X92", text = "Klamydiainfeksjon urogenitalt kvinne"),
  Diagnose(system = DiagnoseType.ICPC2, code = "X99", text = "Sykdom i kvinnelige kjønnsorgan IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y01", text = "Smerte i penis"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y02", text = "Smerte i testikkel/skrotum"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y03", text = "Utflod fra urinrør/penis"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y04", text = "Penis symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y05", text = "Skrotum/testikkel symptomer/plager IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y06", text = "Prostata symptomer/plager"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y07", text = "Impotens organisk betinget"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y08", text = "Seksuelt problem IKA mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y10", text = "Infertilitet mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y13", text = "Sterilisering mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y14", text = "Prevensjon IKA mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y16", text = "Bryst symptomer/plager mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y24", text = "Engstelig for seksuell dysfunksjon mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y25", text = "Engstelig for kjønnssykdom mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y26", text = "Engstelig for kreft i kjønnsorgan mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y27", text = "Engstelig for sykdom i kjønnsorgan IKA mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y28", text = "Redusert funksjonsevne pga problem i kjønnsorgan mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y29", text = "Kjønnsorgan symptomer/plager  IKA mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y70", text = "Syfilis mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y71", text = "Gonokokkinfeksjon mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y72", text = "Genital herpesvirusinfeksjon mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y73", text = "Prostatitt/vesikulitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y74", text = "Orkitt/epididymitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y75", text = "Balanopostitt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y76", text = "Condylomata acuminata mann"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y77", text = "Ondartet svulst i prostata"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y78", text = "Ondartet svulst i mannlige kjønnsorgan IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y79", text = "Godartet/uspesifisert svulst i mannlige kjønnsorgan"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y80", text = "Skade i mannlige kjønnsorgan"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y81", text = "Fimose/overflødig forhud"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y82", text = "Hypospadi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y83", text = "Ikke-descendert testikkel"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y84", text = "Medfødt feil i mannlige kjønnsorgan IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y85", text = "Prostatahyperplasi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y86", text = "Hydrocele"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Y99", text = "Sykdom i mannlige kjønnsorgan IKA"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z01", text = "Problem med økonomi/fattigdom"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z02", text = "Problem med drikkevann/mat"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z03", text = "Problem med bolig/nabolag"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z04", text = "Problem sosialt/kulturelt"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z05", text = "Problem med arbeidsforhold/yrke"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z06", text = "Problem med arbeidsledighet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z07", text = "Problem med utdannelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z08", text = "Problem med sosial velferd/trygd"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z09", text = "Problem med jus/politi"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z10", text = "Problem med helsetjenester/tilgjengelighet"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z11", text = "Problem med det å være syk/compliance"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z12", text = "Problemer mellom samlivspartnere"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z13", text = "Problem med atferd til samlivspartner"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z14", text = "Problem med sykdom hos samlivspartner"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z15", text = "Problem ved tap/dødsfall av samlivspartner"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z16", text = "Problem med/i forhold til barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z18", text = "Problem med sykdom hos barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z19", text = "Problem ved tap/dødsfall av barn"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z20", text = "Problem med forhold til foreldre/familiemedlem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z21", text = "Problem med atferd til forelde/familiemedlem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z22", text = "Problem med sykdom hos foreldre/familiemedlem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z23", text = "Problem ved tap/dødsfall av foreldre/familiemedlem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z24", text = "Problem med forhold til venner"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z25", text = "Problem som følge av vold/traumatisk hendelse"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z27", text = "Engstelig for sosialt problem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z28", text = "Redusert funksjonsevne pga sosialt problem"),
  Diagnose(system = DiagnoseType.ICPC2, code = "Z29", text = "Sosialt problem IKA"),
  /** CODEGEN END **/
)
