/*
 * This source file was generated by the Gradle 'init' task
 */
package no.nav.tsm.diagnoser

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = `ICPC2B.kt`()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
